apiVersion: v1
kind: Namespace
metadata:
  name: rate-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-main
  namespace: rate-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-main
  template:
    metadata:
      labels:
        app: webapp-main
    spec:
      containers:
      - name: webapp
        image: kodekloud/webapp-color
        ports:
        - containerPort: 8080
        env:
        - name: APP_COLOR
          value: "blue"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-main-svc
  namespace: rate-lab
spec:
  selector:
    app: webapp-main
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-admin
  namespace: rate-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-admin
  template:
    metadata:
      labels:
        app: webapp-admin
    spec:
      containers:
      - name: webapp
        image: kodekloud/webapp-color
        ports:
        - containerPort: 8080
        env:
        - name: APP_COLOR
          value: "red"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-admin-svc
  namespace: rate-lab
spec:
  selector:
    app: webapp-admin
  ports:
  - port: 80
    targetPort: 8080